name: Append data data every 10 mins

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      API_ENDPOINT: ${{ secrets.API_BOT_ENDPOINT }}
    steps:
      - name: Append new data
        run: |-
          curl \
            -X GET \
              "$API_BOT_ENDPOINT"
