name: Post Deposits

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      API_ENDPOINT: ${{ secrets.BOT_API_ENDPOINT }}
    steps:
      - name: post deposit bot message
        run: |-
          curl \
            -X GET \
              "$BOT_API_ENDPOINT"
